# Generated by Django 4.2.23 on 2025-07-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_subject',
            field=models.CharField(blank=True, max_length=50, verbose_name='Subject'),
        ),
    ]
