services:
  web:
    build: .
    command: python3 manage.py runserver
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env

  db:
    image: mysql:8.0.43-debian
    restart: "no"
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_DB: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PWD}
      MYSQL_ROOT_PASSWORD: ${DB_PWD}
