#!/bin/bash
#
# Apply rolling update

send_request() {
	max_request="$1"
	while [ "$max_request" -ne 0 ]; do
		sleep 1
		if ! curl --connect-timeout 2 -s \
				 "$(minikube ip 2> /dev/null)" &> /dev/null; then
			echo "request failed !"
		else
			echo "request succeed !"
		fi
		((max_request--))
	done
}

# Ensure minikube is running
if ! minikube status | grep -q "Running"; then
	echo "Starting Minikube ..."
	minikube start
	sleep 15s
fi

# Deploy pod
echo "Deploying Pod ..."
kubectl apply -f blue_deployment.yaml
kubectl apply -f kubeservice.yaml

# Get pod name
POD_NAME=$(kubectl get pods -l version=blue -o jsonpath='{.items[0].metadata.name}')

sleep 15s

# Ensure pods are running and apply database migrations
if kubectl get pod $POD_NAME -o jsonpath='{.status.containerStatuses[0].ready}' &> /dev/null && \
		kubectl get pod $POD_NAME -o jsonpath='{.status.containerStatuses[0].ready}' &> /dev/null; then
	echo "Applying database migration on pod"
	kubectl exec $POD_NAME -- python manage.py migrate
fi

# Update pod image
echo "Updating pod image ..."
sed -i 's/messaging_app:1.0/messaging_app:2.0/g' blue_deployment.yaml

# Deploy new pod version
echo "Starting rolling update ..."
kubectl apply -f blue_deployment.yaml

# Send request while rolling update running
echo "Check for service interruption by sending request continuously ..."
(send_request 60) &
PROCESS_PID=$!
wait $PROCESS_PID

# Monitor rolling update status
echo "Monitoring rolling update progress ..."
kubectl rollout status -w deployment/messaging-app-blue

# Verify rolling update is complete
kubectl get pods

if ! kubectl get pods | grep -q $POD_NAME; then
	echo "Rolling update completed with success !"
else
	echo "Rolling update failed !"
	exit 1
fi

exit 0